### ISSUE TITLE
OSD Name characters

### ISSUE THREAD

**Issue by nagyrobi** [johnboiles/esphome-hdmi-cec#2]
Congratulations, nice project.
Please share with us how to encode any string in OSD name
```
    - opcode: 0x46 # Give OSD name
      then:
        - hdmi_cec.send:
            destination: 0x0
            data: [0x47, 0x65, 0x73, 0x70, 0x68, 0x6F, 0x6D, 0x65] # esphome <- change this to anything
```
