### ISSUE TITLE
Samsung UE50AU7102 (2021)

### ISSUE THREAD

**Issue by nagyrobi** [johnboiles/esphome-hdmi-cec#3]
Congrats for this project.

With the Samsung model above it looks like it doesn't connect automatically the ARC device.
I need to issue the commands manually. Made a button with all commands from your `on_message` section and if I trigger them manually, it will connect.

```
- platform: template
  name: Connect speakers to TV
  on_press:
    - hdmi_cec.send:
        destination: 0x0
        data: [ 0xC1 ]
    - hdmi_cec.send:
        destination: 0xF
        data: [ 0x72, 0x01 ]
    - hdmi_cec.send:
        destination: 0x0
        data: [ 0x7A, 0x7F ]
    - hdmi_cec.send:
        destination: 0x0
        data: [ 0x7A, 0x7F ]
    - hdmi_cec.send:
        destination: 0x0
        data: [ 0x7E, 0x01 ]
    - hdmi_cec.send:
        destination: 0x0
        data: [0x47, 0x65, 0x73, 0x70, 0x68, 0x6F, 0x6D, 0x65] # esphome
    - hdmi_cec.send:
        destination: 0x0
        data: [0x87, 0x00, 0x13, 0x37]
```

After I turn off and back on the TV again, connection is lost with ARC device and volume commands don't come through anymore.
Since I have to connect the ESP to the USB port of the TV, which is powered down when the TV is off, they boot up together.
I tried to add these commands to `on_boot` section of `esphome` with some delay but that's very unstable. Looks like it connects, but looses connection again. After I press the button, it stays connected.

Also, I don't see the OSD name being set by the command.
